apiVersion: keda.sh/v1alpha1 
kind: ScaledObject
metadata:
  name: event-appender-scaler
spec:
  scaleTargetRef:
    name: event-appender
  minReplicaCount: 0 # Change to define how many minimum replicas you want
  maxReplicaCount: 100 #the actual max replica is bounded by the event hub partitation which was configured
  pollingInterval:  5
  cooldownPeriod: 30
  triggers:
  - type: azure-eventhub
    metadata:
      connectionFromEnv: "EVENTHUB_FULL_CONNECTIONSTRING"
      storageConnectionFromEnv: "BLOB_CHECKPOINT_CONNECTIONSTRING"
      consumerGroup: "$Default"
      unprocessedEventThreshold: "5"
      blobContainer: "step1checkpoint"
      checkpointStrategy: "blobMetadata"