apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-generator
  labels:
    app: service-generator
spec:
  selector:
    matchLabels:
      app: service-generator
  template:
    metadata:
      labels:
        app: service-generator
    spec:
      containers:
      - name: service-generator
        image: yaronpr/samples-azure-eventer-service-generator:latest
        env:
        - name: BLOB_CONNECTIONSTRING
          valueFrom:
            secretKeyRef:
              name: secrets-service-generator
              key: blob-connectionstring
        - name: BLOB_UPLOAD_CONNECTIONSTRING
          valueFrom:
            secretKeyRef:
              name: secrets-service-generator
              key: blob-upload-connectionstring
        - name: CONTAINER_NAME
          value: preprocessfiles
        - name: QUEUE_NAME
          value: requests                                  
---
apiVersion: v1
kind: Secret
metadata:
  name: secrets-service-generator
  labels:
    app: service-generator
data:
  blob-upload-connectionstring: RGVmYXVsdEVuZHBvaW50c1Byb3RvY29sPWh0dHBzO0FjY291bnROYW1lPXlhcm9uaW5jb21pbmdmaWxlcztBY2NvdW50S2V5PS9TZDRmWmN2dmRvVGNLVVpIZ0xsR3lFNmhMcVcycVZaREJUYTh2dGRKbUowTmw1Umk3MFd4TGFuQTI2WHl4bzVTeHhRcDJralBiYXNHWUJOZ1l1MnR3PT07RW5kcG9pbnRTdWZmaXg9Y29yZS53aW5kb3dzLm5ldA==  
  blob-connectionstring: RGVmYXVsdEVuZHBvaW50c1Byb3RvY29sPWh0dHBzO0FjY291bnROYW1lPXlhcm9uaW5jb21pbmdmaWxlcztBY2NvdW50S2V5PS9TZDRmWmN2dmRvVGNLVVpIZ0xsR3lFNmhMcVcycVZaREJUYTh2dGRKbUowTmw1Umk3MFd4TGFuQTI2WHl4bzVTeHhRcDJralBiYXNHWUJOZ1l1MnR3PT07RW5kcG9pbnRTdWZmaXg9Y29yZS53aW5kb3dzLm5ldA==

