apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-appender
  labels:
    app: event-appender
spec:
  replicas: 32
  selector:
    matchLabels:
      app: event-appender
  template:
    metadata:
      labels:
        app: event-appender
    spec:
      containers:
      - name: event-appender
        image: yaronpr/samples-azure-eventer-python-appender:latest
        env:        
        - name: EVENTHUB_CONSUMERGROUP
          value: "$Default"
        - name: EVENTHUB_NAME
          value: "step1"
        - name: EVENTHUB_CONNECTIONSTRING
          valueFrom:
            secretKeyRef:
             name: secrets-appender-consumer
             key: eventhub-connectionstring
        - name: BLOB_CHECKPOINT_CONTAINERNAME
          value: step1checkpoint
        - name: BLOB_CHECKPOINT_CONNECTIONSTRING
          valueFrom:
            secretKeyRef:
              name: secrets-appender-consumer
              key: blob-checkpoint-connectionstring
        - name: EVENTHUB_FULL_CONNECTIONSTRING
          valueFrom:
            secretKeyRef:
              name: secrets-appender-consumer
              key: eventhub-full-connectionstring
        - name: BLOB_STORE_CONTAINERNAME
          value: testcontainer
        - name: BLOB_STORE_CONNECTIONSTRING
          valueFrom:
            secretKeyRef:
              name: secrets-appender-consumer
              key: blob-store-connectionstring
        - name: BLOB_STORE_CONTAINERNAME_RESULT
          value: files
        - name: BLOB_STORE_CONNECTIONSTRING_RESULT
          valueFrom:
            secretKeyRef:
              name: secrets-appender-consumer
              key: blob-store-result-connectionstring
        - name: APPINSIGHTS_INSTRUMENTATIONKEY
          valueFrom:
            secretKeyRef:
              name: secrets-appender-consumer
              key: appinsights-insrumentationkey
      nodeSelector:
        "appender": "yes"
---
apiVersion: v1
kind: Secret
metadata:
  name: secrets-appender-consumer
  labels:
    app: event-appender
data:
  eventhub-connectionstring: RW5kcG9pbnQ9c2I6Ly9wNGV2ZW50ZXJodWIuc2VydmljZWJ1cy53aW5kb3dzLm5ldC87U2hhcmVkQWNjZXNzS2V5TmFtZT1Sb290TWFuYWdlU2hhcmVkQWNjZXNzS2V5O1NoYXJlZEFjY2Vzc0tleT1nQy9CcS9hdjAzb3N1WmFqcVpZL2NkS2UvMFRtbGRRMHJ3dDRSQ3JUQzBBPQ==
  blob-checkpoint-connectionstring: RGVmYXVsdEVuZHBvaW50c1Byb3RvY29sPWh0dHBzO0FjY291bnROYW1lPXA0aW5jb21pbmdldmVudHM7QWNjb3VudEtleT1UMmdSS0ErcHErdWRhczVJZUpFTzVLdDNpb0U4U1JZSGxPQ3AwNktUcnRVcENabHFrYXpEVm1ud2FZN0pEaHhvVEJjbnFuSUJUUTBGay9kdWppbWJZQT09O0VuZHBvaW50U3VmZml4PWNvcmUud2luZG93cy5uZXQ=
  eventhub-full-connectionstring: RW5kcG9pbnQ9c2I6Ly9wNGV2ZW50ZXJodWIuc2VydmljZWJ1cy53aW5kb3dzLm5ldC87U2hhcmVkQWNjZXNzS2V5TmFtZT1Sb290TWFuYWdlU2hhcmVkQWNjZXNzS2V5O1NoYXJlZEFjY2Vzc0tleT1nQy9CcS9hdjAzb3N1WmFqcVpZL2NkS2UvMFRtbGRRMHJ3dDRSQ3JUQzBBPTtFbnRpdHlQYXRoPXN0ZXAx
  blob-store-result-connectionstring: RGVmYXVsdEVuZHBvaW50c1Byb3RvY29sPWh0dHBzO0FjY291bnROYW1lPXA0ZXZlbnRlcmFmdGVycHJvY2VzcztBY2NvdW50S2V5PUtzNlhaMkFNTVBtdWdMeStOalluTWR3TXc1cGc2VDJNSE94eWF3ZUdtclhuL1MxaXVMNkJoOUNKam5RZGE3dFhEQWxCTEVyT1Q2K1ZYY1BxSEtlU3p3PT07RW5kcG9pbnRTdWZmaXg9Y29yZS53aW5kb3dzLm5ldA==
  blob-store-connectionstring: RGVmYXVsdEVuZHBvaW50c1Byb3RvY29sPWh0dHBzO0FjY291bnROYW1lPXA0ZXZlbnRlcmluY29taW5nZmlsZXM7QWNjb3VudEtleT1WZXEzUXV5NFZxbTFFQWVrbXdqbWlDaU8zbis1dVpxeU1OMmNaTjF6UHJiR0txa3FuVXc0a0JaSWVWQWQ5RmM3M242dEdDMFE2VDJMOStGTW9JWktsUT09O0VuZHBvaW50U3VmZml4PWNvcmUud2luZG93cy5uZXQ=
  appinsights-insrumentationkey: ZDZhMDAwNjQtNmU5NS00YjI0LWE0MjEtYTFhN2NhMjVlYTcx
