apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-generator
  labels:
    app: service-generator
spec:
  selector:
    matchLabels:
      app: service-generator
  template:
    metadata:
      labels:
        app: service-generator
    spec:
      containers:
      - name: service-generator
        image: yaronpr/samples-azure-eventer-service-generator:latest
        env:
        - name: BLOB_CONNECTIONSTRING
          valueFrom:
            secretKeyRef:
              name: secrets-service-generator
              key: blob-connectionstring
        - name: BLOB_UPLOAD_CONNECTIONSTRING
          valueFrom:
            secretKeyRef:
              name: secrets-service-generator
              key: blob-upload-connectionstring
        - name: CONTAINER_NAME
          value: testcontainer
        - name: QUEUE_NAME
          value: requests
        - name: APPINSIGHTS_INSTRUMENTATIONKEY
          valueFrom:
            secretKeyRef:
              name: secrets-service-generator
              key: appinsights-insrumentationkey
      nodeSelector:
        "gen2": "yes"
---
apiVersion: v1
kind: Secret
metadata:
  name: secrets-service-generator
  labels:
    app: service-generator
data:
  blob-upload-connectionstring: RGVmYXVsdEVuZHBvaW50c1Byb3RvY29sPWh0dHBzO0FjY291bnROYW1lPXA0ZXZlbnRlcmluY29taW5nZmlsZXM7QWNjb3VudEtleT1WZXEzUXV5NFZxbTFFQWVrbXdqbWlDaU8zbis1dVpxeU1OMmNaTjF6UHJiR0txa3FuVXc0a0JaSWVWQWQ5RmM3M242dEdDMFE2VDJMOStGTW9JWktsUT09O0VuZHBvaW50U3VmZml4PWNvcmUud2luZG93cy5uZXQ=
  blob-connectionstring: RGVmYXVsdEVuZHBvaW50c1Byb3RvY29sPWh0dHBzO0FjY291bnROYW1lPXA0ZXZlbnRzcXVldWU7QWNjb3VudEtleT1YQis2bFk3UEFjNmtBVnJRQ2hDQ0ZlMXdYMzA0TlJBdVdCbmMvbkl1U2NvQ09UVE5IREFZeWV2N1ZMSHlYb2VaaWhLVzkxQS9GTG0wZm95SnREMHNpQT09O0VuZHBvaW50U3VmZml4PWNvcmUud2luZG93cy5uZXQ=
  appinsights-insrumentationkey: ZDZhMDAwNjQtNmU5NS00YjI0LWE0MjEtYTFhN2NhMjVlYTcx
