name: Docker Image CI

on:
  push:
    branches: [ main ]
    paths: 'src/Samples.Azure.Eventer.ServiceGenerator/**' 

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Docker Login
      uses: docker/login-action@v1.6.0
      with:
        username: yaronpr
        password: ${{ secrets.DOCKERHUB }}      
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build ./src/Samples.Azure.Eventer.ServiceGenerator/ --file src/Samples.Azure.Eventer.ServiceGenerator/Dockerfile --tag yaronpr/samples-azure-eventer-service-generator:latest
    - name: Push the Docker image
      run: docker push yaronpr/samples-azure-eventer-service-generator:latest
